M48
; DRILL file {KiCad (6.0.7)} date Mon Mar 20 21:56:41 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-20T21:56:41-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.946
%
G90
G05
T1
X143.718Y-131.018
X143.718Y-278.328
X278.328Y-131.018
X278.328Y-278.328
T0
M30
